services:
  api:
    build: .
    container_name: api-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=api_nest
    networks:
      app-network: {} # Corrige a referência

networks:
  app-network:
    # Garante que a rede está definida
    driver: bridge
